image: d.ims.io/channels/dotnet-gitlab-ci-agent:v1.1.0-rc3

stages:
  - build
  - publish

build_debug:
  stage: build
  script: ./build.sh -t Default -c Debug
  except:
    - master
    - tags

build_release:
  stage: build
  script: ./build.sh -t Default -c Release
  only:
    - master

## PUBLISHING
###########

# all feature branches will build and publish pre-release versions of nuget packages
publish_prerelease:
  stage: publish
  script: ./build.sh -t BuildAndPublish -c Debug
  except:
    - master
    - tags

# IFF there's a tag attached to this rev, we'll publish release versions of packages
publish_release:
  stage: publish
  script: ./build.sh -t BuildAndPublish -c Release
  only:
    - tags
