language: csharp
os:
  - linux

# .NET CLI require Ubuntu 14.04
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8

mono:
  - 4.4.2

dotnet: 1.0.4

before_script:
  - '[[ $TRAVIS_TAG =~ (^v[0-9]+.[0-9]+.[0-9]+) ]] && CONFIGURATION="Release" || CONFIGURATION="Debug"'

script:
  - ./build.sh -t Default -c $CONFIGURATION --verbosity diagnostic

after_success:
  - ./build.sh -t Publish -c $CONFIGURATION --verbosity diagnostic

cache:
  directories:
    - .packages
    - .tools
