language: csharp
os:
  - linux

# .NET CLI require Ubuntu 14.04
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8

mono:
  - 4.4.2

dotnet: 1.0.4

script:
  - ./build.sh --verbosity diagnostic

cache:
  directories:
    - .packages
    - .tools
